46 sorting filters
AgiliaErnis/restaurateur pull request #92
Opened 2021-05-16 15:19 UTC by AniSanikidze

- Fixed bugs
- Replaced old sorting code with a new one, based on the backend logic.
- Added "Without sorting" option. This option shows up only when the other sorting option is chosen.

2021-05-16 20:47 UTC, AgiliaErnis approved these changes

2021-05-17 16:23 UTC, Lucius1010011010 approved these changes

2021-05-17 17:20 UTC, adzai requested changes
If I go to restaurants and choose price descending right away, the query to backend is `/restaurants?radius=ignore&&sort=price-descending`, which doesn't do anything.
If I choose something else like rating and then price descending, the behavior is as expected -> `/restaurants?radius=ignore&&sort=price-desc`

Also, as you can see above, there is always a double `&&` before sort. Should get cleaned up, I don't think it's causing any issues right now but just to be safe.

2021-05-18 10:16 UTC, adzai approved these changes
Everything seems to work fine now.

2021-05-18 10:55 UTC, merged